hg: explicitly check that peer lookup object has instance() if call failed
If a "thing" is callable but raises TypeError for some reason, a callable
object would be returned. Thereafter, unfriendly traceback would be displayed:

  Traceback (most recent call last):
    ...
    File "mercurial/hg.pyc", line 119, in _peerorrepo
      obj = _peerlookup(path).instance(ui, path, create)
  AttributeError: 'function' object has no attribute 'instance'

Instead, we should show the reason why "thing(path)" didn't work:

  Traceback (most recent call last):
    ...
    File "hggit/__init__.py", line 89, in _local
      p = urlcls(path).localpath()
  TypeError: 'NoneType' object is not callable

If a "thing" is not callable, it must be a module or an object that implements
instance(). If that module didn't have instance(), the error message would be
"<unloaded module 'foo'> object is not callable". It doesn't make perfect sense,
but it isn't so bad as it can blame which module went wrong.